"""Campership scenarios (sub-project 9b): sizing moves, labels and codes, results, and fit to budget. Pure: no I/O."""

from bunking.financial_aid.scenarios.describe import (
    CHANGE_MAX_CHARS,
    change_phrases,
    describe,
    starting_point_code,
    variant_code,
)
from bunking.financial_aid.scenarios.fit import (
    FIT_HIGH,
    FIT_LOW,
    FIT_STEP,
    FitKind,
    FitResult,
    fit_margin,
    fit_tier_shift,
    tightest_pool,
)
from bunking.financial_aid.scenarios.request_set import RequestSet, RequestSetBasis, RequestSetNote, request_set_note
from bunking.financial_aid.scenarios.results import (
    PoolResult,
    Round2TierRow,
    ScenarioResults,
    TableTierRow,
    TierRow,
    round1_amount,
    round1_by_request,
    scenario_results,
    up_down,
)
from bunking.financial_aid.scenarios.sizing import (
    SIZING_LEVERS,
    SizingError,
    SizingLever,
    SizingLeverKey,
    apply_sizing,
    dollar_for_dollar,
    nudge,
    shift_round1_tables,
    widen_bands,
    with_dollar_for_dollar,
    with_minimum,
)

__all__ = [
    "CHANGE_MAX_CHARS",
    "FIT_HIGH",
    "FIT_LOW",
    "FIT_STEP",
    "SIZING_LEVERS",
    "FitKind",
    "FitResult",
    "PoolResult",
    "RequestSet",
    "RequestSetBasis",
    "RequestSetNote",
    "Round2TierRow",
    "ScenarioResults",
    "SizingError",
    "SizingLever",
    "SizingLeverKey",
    "TableTierRow",
    "TierRow",
    "apply_sizing",
    "change_phrases",
    "describe",
    "dollar_for_dollar",
    "fit_margin",
    "fit_tier_shift",
    "nudge",
    "request_set_note",
    "round1_amount",
    "round1_by_request",
    "scenario_results",
    "shift_round1_tables",
    "starting_point_code",
    "tightest_pool",
    "up_down",
    "variant_code",
    "widen_bands",
    "with_dollar_for_dollar",
    "with_minimum",
]
