"""County from a US billing ZIP (app spec §6.3 item 2, D32; Decision 8a of the slice 1 reads part 2 plan). The table is
generated by scripts/data/seed_zip_counties.py from the Census ZCTA-to-county file: a ZIP no county holds the majority
of, or one with no ZCTA, isn't in it."""

from __future__ import annotations

import json
from functools import cache
from importlib.resources import files


@cache
def _table() -> dict[str, str]:
    text = files("bunking.geo_normalizer.data").joinpath("us_zip_counties.json").read_text(encoding="utf-8")
    table: dict[str, str] = json.loads(text)
    return table


def county_for_postal_code(postal_code: str) -> str | None:
    digits = postal_code.strip()[:5]
    return _table().get(digits) if len(digits) == 5 and digits.isdecimal() else None
