/**
 * Re-exports of generated API types with friendly aliases.
 *
 * Auto-generated types live in `api-generated.ts` (produced by
 * `npm run generate:api-types`). Direct use of the generated
 * `components["schemas"]["Foo"]` syntax is verbose; this file provides
 * concise aliases for the types used widely across the frontend.
 *
 * Import from here, not directly from `api-generated.ts`.
 *
 * Generated by: npm run generate:api-types
 * Source: api/schemas/social_graph.py + bunking/graph/scope_filter.py
 */

import type { components } from './api-generated'

// ── Social graph types ────────────────────────────────────────────────────────

/** Node in the social graph. Mirrors Python `SocialGraphNode` Pydantic model. */
export type ApiSocialGraphNode = components['schemas']['SocialGraphNode']

/** Edge in the social graph. Mirrors Python `SocialGraphEdge` Pydantic model. */
export type ApiSocialGraphEdge = components['schemas']['SocialGraphEdge']

/** Edge crossing the active scope boundary. Mirrors Python `CrossScopeEdge`. */
export type ApiCrossScopeEdge = components['schemas']['CrossScopeEdge']

/** Complete social graph response. Mirrors Python `SocialGraphResponse`. */
export type ApiSocialGraphResponse = components['schemas']['SocialGraphResponse']

/** Bunk-level subgraph response. Mirrors Python `BunkGraphResponse`. */
export type ApiBunkGraphResponse = components['schemas']['BunkGraphResponse']
