/**
 * Re-exports of generated API types with friendly aliases.
 *
 * Auto-generated types live in `api-generated/types.gen.ts` (produced by
 * `npm run generate:api-types`, with an `index.ts` barrel re-exporting
 * each schema as a flat top-level name). Aliases here keep import sites
 * concise and decouple consumer code from codegen output naming.
 *
 * Import from here, not directly from `api-generated/`.
 *
 * Generated by: npm run generate:api-types
 * Source: api/schemas/social_graph.py + bunking/graph/scope_filter.py
 *
 * ── Pydantic ↔ TypeScript gotcha ─────────────────────────────────────────────
 * `@hey-api/openapi-ts` treats Pydantic fields with a default value as
 * OPTIONAL in TypeScript (the key may be omitted, and the value type
 * stays non-nullable). E.g. `cross_scope: bool = False` becomes
 * `cross_scope?: boolean` and `centrality: float = 0.0` becomes
 * `centrality?: number`.
 *
 * Practical implications:
 *   - Code that *reads* these fields should provide a fallback matching
 *     the Python default (e.g. `node.centrality ?? 0`) — the server
 *     always populates them, but TS can't know that.
 *   - Code that *constructs* these objects (test fixtures, mocks) MAY
 *     omit defaulted keys entirely.
 *   - To make a field nullable on the wire (key always present, value
 *     can be null), mark it `Optional[T] = None` in Python — the key
 *     becomes optional AND the value type becomes `T | null`.
 */

import type {
  AcceptedIn,
  AidPostingLine,
  AidRulesInput,
  AidRulesOutput,
  AnswerOut,
  ApplicationDetailResponse,
  ApprovedRulesOut,
  ApprovedSectionOut,
  AskIn,
  BudgetResponse,
  BunkGraphResponse,
  CamperJourneyCounts,
  CamperJourneyResponse,
  CamperJourneyRow,
  CancellationIn,
  CancellationOut,
  CellOut,
  ConfirmationOut,
  ConfirmationStateOut,
  CountOut,
  DecisionTypeLineOut,
  CorrectionCreate,
  CorrectionOut,
  CrossScopeEdge,
  DecisionTypeOutput,
  DecisionWriteOut,
  DefinitionsResponse,
  DocumentIn,
  DraftOut,
  DraftSectionOut,
  DuplicateMark,
  EditorPreviewOut,
  EvaluateIn,
  EvaluateOut,
  ExpectedOut,
  FieldChangeOut,
  GrantRowOut,
  GridRowOut,
  HeadcountSet,
  HistoryEntryOut,
  HistoryOperationDetailOut,
  HistoryOperationOut,
  HistoryPageOut,
  HistoryRowOut,
  HoldReleaseIn,
  HouseholdCardOut,
  HouseholdLinkRow,
  HouseholdPageResponse,
  HouseholdRequestOut,
  HouseholdShareSet,
  HouseholdTotalsOut,
  IncentiveRule,
  IncomeOut,
  IssueOut,
  JumpIndexHousehold,
  JumpIndexResponse,
  KeepIn,
  LeverEffectOut,
  LoadIn,
  ManualHoldIn,
  OptionOut,
  PermissionEntry,
  PermissionRegistryResponse,
  PermissionScreen,
  PostedIn,
  PreviewIn,
  ProgramProfile,
  ReceiptOut,
  PoolBudgetOut,
  RemainingResponse,
  ResultsOut,
  RoundCountsOut,
  SensitivityOut,
  SnapshotOut,
  TodayLineOut,
  TodayResponse,
  RequestOut,
  RequestsGridResponse,
  Round3AmountIn,
  Round3ApprovalIn,
  RoundOut,
  RulesDraftOut,
  SectionStatus,
  SessionResolve,
  ShareLineOut,
  SocialGraphEdge,
  SocialGraphNode,
  SocialGraphResponse,
  UnpostIn,
  ValidationIssue,
  WorkspaceOut,
} from './api-generated'

// ── Social graph types ────────────────────────────────────────────────────────

/** Node in the social graph. Mirrors Python `SocialGraphNode` Pydantic model. */
export type ApiSocialGraphNode = SocialGraphNode

/** Edge in the social graph. Mirrors Python `SocialGraphEdge` Pydantic model. */
export type ApiSocialGraphEdge = SocialGraphEdge

/** Edge crossing the active scope boundary. Mirrors Python `CrossScopeEdge`. */
export type ApiCrossScopeEdge = CrossScopeEdge

/** Complete social graph response. Mirrors Python `SocialGraphResponse`. */
export type ApiSocialGraphResponse = SocialGraphResponse

/** Bunk-level subgraph response. Mirrors Python `BunkGraphResponse`. */
export type ApiBunkGraphResponse = BunkGraphResponse

// ── Camper journey (kindred#2776) ─────────────────────────────────────────────

/** A person's journey as of one viewed year. Mirrors Python `CamperJourneyResponse`. */
export type ApiCamperJourneyResponse = CamperJourneyResponse

/** One prior-year row, snake_case on the wire. Mirrors Python `CamperJourneyRow`. */
export type ApiCamperJourneyRow = CamperJourneyRow

/** The journey header's counts. Mirrors Python `CamperJourneyCounts`. */
export type ApiCamperJourneyCounts = CamperJourneyCounts

// ── Camperships (financial aid) ───────────────────────────────────────────────

/** The Remaining line's read (D48). Mirrors Python `RemainingResponse`. */
export type ApiAidRemaining = RemainingResponse

/** Today (§6.4). Mirrors Python `TodayResponse` and `TodayLineOut`. */
export type ApiAidToday = TodayResponse
export type ApiAidTodayLine = TodayLineOut

/** The jump box's index (§3.5, slice 1's read). Mirrors Python `JumpIndexResponse`. */
export type ApiAidJumpIndex = JumpIndexResponse
export type ApiAidJumpHousehold = JumpIndexHousehold

/** A surface's numbered definition notes (§4.8, slice 1's read). Mirrors Python `DefinitionsResponse`. */
export type ApiAidDefinitions = DefinitionsResponse

/** The Users page's permission registry (code defaults). Mirrors Python `PermissionRegistryResponse`. */
export type ApiPermissionRegistry = PermissionRegistryResponse
export type ApiPermissionEntry = PermissionEntry
export type ApiPermissionScreen = PermissionScreen

/** The Requests grid's read (§6.1). Mirrors Python `RequestsGridResponse`. */
export type ApiAidGrid = RequestsGridResponse
export type ApiAidGridRow = GridRowOut
export type ApiAidRound = RoundOut
/** A Requests view a row is in (#2924's `QueueOut`). */
export type ApiAidQueue = NonNullable<GridRowOut['queues']>[number]
/** A request's confirmation state (D59) and its cancellation (D101). Mirror Python's models (M4). */
export type ApiAidConfirmation = ConfirmationOut
export type ApiAidCancellation = CancellationOut
/** The request editor's live preview (§4.6, D22). Mirrors Python `EditorPreviewOut`. */
export type ApiAidPreview = EditorPreviewOut
export type ApiAidPreviewIn = PreviewIn
/** A family's Round 2 or Round 3 ask. Mirrors Python `AskIn`. */
export type ApiAidAskIn = AskIn
/** The Posted tick, one row or many (D51, D52). Mirrors Python `PostedIn`. */
export type ApiAidPostedIn = PostedIn
/** The Accepted tick (D47). Mirrors Python `AcceptedIn`. */
export type ApiAidAcceptedIn = AcceptedIn
/** The household page's decision writes (§6.3). Each mirrors its Python model. */
export type ApiAidUnpostIn = UnpostIn
export type ApiAidRound3AmountIn = Round3AmountIn
export type ApiAidRound3ApprovalIn = Round3ApprovalIn
export type ApiAidHoldReleaseIn = HoldReleaseIn
export type ApiAidManualHoldIn = ManualHoldIn
export type ApiAidCancellationIn = CancellationIn
/** What a decisions write did. Mirrors Python `DecisionWriteOut`. */
export type ApiAidWriteOut = DecisionWriteOut

/** The household page's read (§6.3). Mirrors Python `HouseholdPageResponse` and its parts. */
export type ApiAidHouseholdPage = HouseholdPageResponse
export type ApiAidHouseholdRequest = HouseholdRequestOut
export type ApiAidHouseholdCard = HouseholdCardOut
export type ApiAidHouseholdTotals = HouseholdTotalsOut
export type ApiAidConfirmationState = ConfirmationStateOut
export type ApiAidShareLine = ShareLineOut
export type ApiAidReceipt = ReceiptOut
export type ApiAidIncome = IncomeOut
export type ApiAidAnswer = AnswerOut
export type ApiAidHistoryEntry = HistoryEntryOut
export type ApiAidPostingLine = AidPostingLine
export type ApiAidGrantRow = GrantRowOut
export type ApiAidExpected = ExpectedOut

/** A household's application with its intake requests (flags, headcounts, duplicates). Mirrors Python `ApplicationDetailResponse`. */
export type ApiAidApplication = ApplicationDetailResponse
export type ApiAidRequestOut = RequestOut
/** The casework forms' writes (§6.3). Each mirrors its Python model. */
export type ApiAidCorrectionIn = CorrectionCreate
export type ApiAidCorrectionOut = CorrectionOut
export type ApiAidHouseholdShareIn = HouseholdShareSet
export type ApiAidSessionIn = SessionResolve
export type ApiAidDuplicateIn = DuplicateMark
export type ApiAidHeadcountIn = HeadcountSet
export type ApiAidHouseholdLink = HouseholdLinkRow
/** A hold, note or check on a request. Mirrors Python `IssueOut`. */
export type ApiAidIssue = IssueOut

/** Rounds & budget (spec §7.2; slice 2). Mirrors Python `BudgetResponse` and its parts. */
export type ApiAidBudget = BudgetResponse
export type ApiAidBudgetPool = PoolBudgetOut
export type ApiAidBudgetCell = CellOut
export type ApiAidRoundCounts = RoundCountsOut
/** "3 families · 4 requests" (principle 7). Mirrors Python `CountOut`. */
export type ApiAidCount = CountOut
/** One decision-type line of a pool's budget. Mirrors Python `DecisionTypeLineOut`. */
export type ApiAidDecisionTypeLine = DecisionTypeLineOut

/** Season › Rules (spec §7.5; D39, D76). Mirrors Python `ApprovedRulesOut`, `RulesDraftOut` and their parts. */
export type ApiAidApprovedRules = ApprovedRulesOut
export type ApiAidApprovedSection = ApprovedSectionOut
export type ApiAidRulesDraft = RulesDraftOut
export type ApiAidDraftSection = DraftSectionOut
export type ApiAidSectionStatus = SectionStatus
export type ApiAidFieldChange = FieldChangeOut
export type ApiAidValidationIssue = ValidationIssue
/** One of the rules document's fourteen sections (Python `SectionName`). */
export type ApiAidRulesSection = DraftSectionOut['section']
/** The rules document as the server sends it (decimals as strings), and as a write sends it back. */
export type ApiAidRulesDocument = AidRulesOutput
export type ApiAidRulesDocumentIn = AidRulesInput

/** Rules records the document holds by key (`{[key]: unknown | T}`), named so the editor can read their choices. Mirrors Python `ProgramProfile`. */
export type ApiAidProgramProfile = ProgramProfile
/** Mirrors Python `IncentiveRule`. */
export type ApiAidIncentiveRule = IncentiveRule
/** Mirrors Python `DecisionType`. */
export type ApiAidDecisionType = DecisionTypeOutput

/** Season › History (spec §7.6; D49): the season's log, one line per operation. Mirrors Python `HistoryPageOut`, `HistoryOperationOut`, `HistoryOperationDetailOut` and `HistoryRowOut`. */
export type ApiAidHistoryPage = HistoryPageOut
export type ApiAidHistoryOperation = HistoryOperationOut
export type ApiAidHistoryOperationDetail = HistoryOperationDetailOut
export type ApiAidHistoryRow = HistoryRowOut
/** Mirrors Python `HistoryKind`. */
export type ApiAidHistoryKind = HistoryOperationOut['kind']

/** Season › Scenarios (spec §7.4; D35–D38; SP9b). Mirrors Python `WorkspaceOut` and its parts. */
export type ApiAidScenarioWorkspace = WorkspaceOut
export type ApiAidScenarioDraft = DraftOut
export type ApiAidScenarioOption = OptionOut
export type ApiAidScenarioSnapshot = SnapshotOut
export type ApiAidScenarioResults = ResultsOut
export type ApiAidScenarioEvaluateIn = EvaluateIn
export type ApiAidScenarioEvaluation = EvaluateOut
export type ApiAidScenarioDocumentIn = DocumentIn
export type ApiAidScenarioLoadIn = LoadIn
export type ApiAidScenarioKeepIn = KeepIn
export type ApiAidScenarioSensitivity = SensitivityOut
export type ApiAidLeverEffect = LeverEffectOut
