/**
 * Re-exports of generated API types with friendly aliases.
 *
 * Auto-generated types live in `api-generated.ts` (produced by
 * `npm run generate:api-types`). Direct use of the generated
 * `components["schemas"]["Foo"]` syntax is verbose; this file provides
 * concise aliases for the types used widely across the frontend.
 *
 * Import from here, not directly from `api-generated.ts`.
 *
 * Generated by: npm run generate:api-types
 * Source: api/schemas/social_graph.py + bunking/graph/scope_filter.py
 *
 * ── Pydantic ↔ TypeScript gotcha ─────────────────────────────────────────────
 * `openapi-typescript` treats Pydantic fields with a default value as
 * REQUIRED in TypeScript, even though they're omittable on the server side.
 * E.g. `metadata: dict = {}` and `cross_scope: bool = False` both become
 * required keys in the generated type.
 *
 * Practical implication: any code that *constructs* one of these objects
 * (test fixtures, mocks, cached scenarios) must include every defaulted
 * field — TS will not let you omit it. Adding a new defaulted-but-not-
 * `Optional[...]` field to a Pydantic schema is therefore a TS-breaking
 * change for every consumer that builds these shapes by hand.
 *
 * To make a field truly optional in TS, mark it `Optional[T] = None` in
 * Python (then it becomes `T | null` and the key becomes optional).
 */

import type { components } from './api-generated'

// ── Social graph types ────────────────────────────────────────────────────────

/** Node in the social graph. Mirrors Python `SocialGraphNode` Pydantic model. */
export type ApiSocialGraphNode = components['schemas']['SocialGraphNode']

/** Edge in the social graph. Mirrors Python `SocialGraphEdge` Pydantic model. */
export type ApiSocialGraphEdge = components['schemas']['SocialGraphEdge']

/** Edge crossing the active scope boundary. Mirrors Python `CrossScopeEdge`. */
export type ApiCrossScopeEdge = components['schemas']['CrossScopeEdge']

/** Complete social graph response. Mirrors Python `SocialGraphResponse`. */
export type ApiSocialGraphResponse = components['schemas']['SocialGraphResponse']

/** Bunk-level subgraph response. Mirrors Python `BunkGraphResponse`. */
export type ApiBunkGraphResponse = components['schemas']['BunkGraphResponse']
