#!/usr/bin/env python3
"""Generate frontend city coordinate data and backend lookup JSON from uscities.csv.

Reads the SimpleMaps uscities.csv and generates:
1. frontend/src/data/cityGeo.ts — US_CITY_COORDS and US_CITY_STATES lookups
2. bunking/geo_normalizer/data/us_cities.json — lookup + location metadata

All city+state variants are emitted (no dedup). Canonical format is "City, ST".

Usage:
    uv run python scripts/data/seed_city_coords.py --source path/to/uscities.csv
"""

import argparse
import csv
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CSV_PATH = REPO_ROOT / "uscities.csv"
OUTPUT_PATH = REPO_ROOT / "frontend" / "src" / "data" / "cityGeo.ts"
JSON_OUTPUT_PATH = REPO_ROOT / "bunking" / "geo_normalizer" / "data" / "us_cities.json"


def load_csv(csv_path: Path) -> list[dict[str, str]]:
    """Load uscities.csv rows."""
    if not csv_path.exists():
        print(f"Error: {csv_path} not found", file=sys.stderr)
        sys.exit(1)
    with open(csv_path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def generate(csv_path: Path) -> None:
    """Generate cityGeo.ts and us_cities.json with all city+state variants."""
    rows = load_csv(csv_path)
    print(f"  Loaded {len(rows)} rows from {csv_path.name}", file=sys.stderr)

    coords: dict[str, tuple[float, float]] = {}  # "City, ST" -> (lat, lng)
    states_map: dict[str, str] = {}  # "City, ST" -> "ST"
    lookup_multi: dict[str, list[str]] = {}  # lowercase_name -> ["City, ST", ...]
    location: dict[str, dict[str, str]] = {}  # "City, ST" -> {"state": "ST"}

    for row in rows:
        name = row["city"].strip()
        state = row["state_id"].strip()
        try:
            lat = float(row["lat"])
            lng = float(row["lng"])
        except ValueError, KeyError:
            continue

        canonical = f"{name}, {state}"
        coords[canonical] = (lat, lng)
        states_map[canonical] = state
        location[canonical] = {"state": state}

        name_lower = name.lower()
        if name_lower not in lookup_multi:
            lookup_multi[name_lower] = []
        if canonical not in lookup_multi[name_lower]:
            lookup_multi[name_lower].append(canonical)

    print(f"  {len(coords)} city+state variants from {len(lookup_multi)} unique names", file=sys.stderr)

    # Generate TypeScript — all keys contain commas so they always need quoting
    lines = [
        "/**",
        " * US city coordinates and state mappings.",
        " *",
        " * Auto-generated by scripts/data/seed_city_coords.py from SimpleMaps uscities.csv.",
        " * Do not edit manually - re-run the script to update.",
        " *",
        f" * {len(coords)} cities included.",
        " */",
        "",
        "import type { LatLng } from './californiaGeo'",
        "",
        "export const US_CITY_COORDS: Record<string, LatLng> = {",
    ]

    for canonical in sorted(coords.keys()):
        lat, lng = coords[canonical]
        key = repr(canonical)
        lines.append(f"  {key}: [{lat}, {lng}],")

    lines.append("}")
    lines.append("")
    lines.append("export const US_CITY_STATES: Record<string, string> = {")

    for canonical in sorted(states_map.keys()):
        key = repr(canonical)
        state = repr(states_map[canonical])
        lines.append(f"  {key}: {state},")

    lines.append("}")
    lines.append("")

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    size_kb = OUTPUT_PATH.stat().st_size / 1024
    print(f"  Generated {OUTPUT_PATH.name} ({size_kb:.0f} KB)", file=sys.stderr)

    # Generate us_cities.json with multi-variant lookup + location metadata
    json_data = {
        "lookup": dict(sorted(lookup_multi.items())),
        "location": dict(sorted(location.items())),
    }

    JSON_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(JSON_OUTPUT_PATH, "w") as f:
        json.dump(json_data, f, indent=2)

    json_size_kb = JSON_OUTPUT_PATH.stat().st_size / 1024
    print(f"  Generated {JSON_OUTPUT_PATH.name} ({json_size_kb:.0f} KB)", file=sys.stderr)
    print(
        f"  {len(lookup_multi)} names in lookup, {len(location)} canonicals with location",
        file=sys.stderr,
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate frontend city coordinate data")
    parser.add_argument(
        "--source",
        type=Path,
        default=None,
        help="Path to uscities.csv (default: auto-discover in repo root)",
    )
    args = parser.parse_args()

    csv_path = args.source or CSV_PATH
    print(f"Generating city coordinates from {csv_path}...", file=sys.stderr)

    generate(csv_path)
    print("Done.", file=sys.stderr)


if __name__ == "__main__":
    main()
