// UI components barrel export
export { Modal } from './Modal'
export { FloatingQueueBadge } from './FloatingQueueBadge'
export type { FloatingQueueBadgeProps } from './FloatingQueueBadge'
export { TitleSwitcher } from './TitleSwitcher'
export type { TitleSwitcherOption, TitleSwitcherProps } from './TitleSwitcher'
export { Tooltip } from './Tooltip'
export type { TooltipProps } from './Tooltip'
export { SortableColumnHeader } from './SortableColumnHeader'
export type { SortableColumnHeaderProps, SortDirection } from './SortableColumnHeader'
