"""One-shot heal for bunk_requests rows mis-declined by Phase C target-decline.

Background:
    `compute_target_decline_actions` in
    `bunking/sync/bunk_request_processor/orchestrator/target_decline.py` used to
    treat negative-hash placeholder `requestee_id` values (generated by
    `orchestrator.generate_unresolved_person_id` for unresolved names) as if
    they were real cm_ids. The lookup against active enrollments always
    failed, so every unresolved-name row was flipped to
    `status='declined', disposition_reason='target_not_attending'` — surfacing
    in the UI as "this camper isn't attending" when the truth was "we couldn't
    resolve this name to anyone." Phase C is now guarded; this script heals
    the historical rows.

Heal criteria (intersection):
    - `requestee_id < 0`          (negative-hash placeholder, not a real cm_id)
    - `status = 'declined'`
    - `disposition_reason = 'target_not_attending'`

Heal action:
    `status` → 'pending', `disposition_reason` → 'needs_review'.
    The row lands back in staff review where unresolved names belong.

Usage:
    cd /path/to/kindred && docker compose down
    uv run python scripts/target_decline_negative_id_backfill.py /path/to/pb_data/data.db

The script does not start or stop the docker stack itself — the operator must
ensure the SQLite file is not held by PocketBase before running. Idempotent.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path


def backfill(db_path: Path) -> dict[str, int]:
    """Heal mis-declined unresolved-name rows. Returns scanned/updated counts."""
    conn = sqlite3.connect(db_path)
    try:
        cursor = conn.execute(
            "SELECT id FROM bunk_requests WHERE requestee_id < 0 AND status = ? AND disposition_reason = ?",
            ("declined", "target_not_attending"),
        )
        ids = [row[0] for row in cursor.fetchall()]
        if ids:
            conn.executemany(
                "UPDATE bunk_requests SET status = ?, disposition_reason = ? WHERE id = ?",
                [("pending", "needs_review", row_id) for row_id in ids],
            )
            conn.commit()
        return {"scanned": len(ids), "updated": len(ids)}
    finally:
        conn.close()


def main() -> int:
    parser = argparse.ArgumentParser(description="Heal negative-id Phase C target-decline mis-classifications")
    parser.add_argument("db_path", type=Path, help="Path to PocketBase SQLite file")
    args = parser.parse_args()
    if not args.db_path.is_file():
        print(f"Error: {args.db_path} is not a file", file=sys.stderr)
        return 1
    # Refuse to touch the DB if a non-empty -wal sidecar exists — PocketBase
    # may still be running, or crashed mid-write. Operator must stop PB first
    # so SQLite can flush WAL frames into the main file before we read/write.
    wal_path = args.db_path.with_suffix(args.db_path.suffix + "-wal")
    if wal_path.exists() and wal_path.stat().st_size > 0:
        print(
            f"Error: {wal_path} is non-empty — PocketBase may still be active.\n"
            f"Stop the container first, then checkpoint:\n"
            f"  sqlite3 {args.db_path} 'PRAGMA wal_checkpoint(TRUNCATE);'\n"
            f"Then re-run this script.",
            file=sys.stderr,
        )
        return 1
    result = backfill(args.db_path)
    print(f"Scanned:  {result['scanned']} (negative-id rows mis-declined as target_not_attending)")
    print(f"Updated:  {result['updated']} (reset to status=pending, disposition_reason=needs_review)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
