/**
 * kindred#2763 — EVERY RENDERING CALL SITE'S CURRENT OUTPUT, PINNED.
 *
 * The owner's 2026-09-23 ruling for #2763 is "consolidation ONLY,
 * pixel-identical": fold the session-name shorteners into one entry point
 * with a closed set of forms, and change no rendered text. This file is the
 * evidence. Each group below names the call sites it covers and the function
 * they called before the move, and pins a corpus of realistic names — one or
 * more per program (summer main, embedded, AG, Quest, teen, family, adult) —
 * against the literal output that function produced on the base the move
 * started from (`feature/adult-capacity-warning` @ 82133694).
 *
 * The expected strings are LITERALS on purpose. They were generated by running
 * the old functions, not by reading their source, so a rule that moved wrong
 * cannot also move the expectation with it.
 *
 * Where a call site's inputs are narrower than the corpus, the group says so
 * and pins only what can reach it (CamperCard's last-year line reads
 * `CamperHistoryProvider`, which admits at-camp session types only).
 *
 * Reconciling the disparities these pins preserve — five renderings of one AG
 * session, three of one family weekend — is #2790, and deliberately not here.
 */
import { describe, expect, it } from 'vitest'

import {
  formatAgSessionLabel,
  getFormattedSessionName,
  getSessionChartLabel,
  getSessionDisplayName,
  getSessionDisplayNameFromString,
  getSessionShortName,
  getSessionShorthand,
  shortenSessionName,
} from './sessionDisplay'
import { shortWeekendName, weekendLabel, weekendSlug } from '../components/weekend/weekendNames'
import { sessionName } from './sessionName'
import type { SessionNameForm } from './sessionName'
import type { Session } from '../types/app-types'

type Pin = readonly [name: string, sessionType: string | undefined, expected: string]

interface CallSiteGroup {
  group: string
  /** The form of `sessionName` these call sites map onto. */
  form: SessionNameForm
  /** What the call sites called before the move. */
  was: string
  sites: string[]
  legacy: (name: string, sessionType: string | undefined) => string
  pins: Pin[]
}

const CALL_SITE_GROUPS: CallSiteGroup[] = [
  {
    group: 'short-untyped',
    form: 'short',
    was: 'shortenSessionName(name)',
    sites: [
      'metrics/DrillDownModal.tsx (x3, attendee session cells)',
      'metrics/registration/ForecastPage.tsx (session column)',
    ],
    legacy: (name) => shortenSessionName(name),
    pins: [
      ['Session 2', undefined, 'Session 2'],
      ['Session 3', undefined, 'Session 3'],
      ['Session 2 (Grades 4-6)', undefined, 'Session 2 (Grades 4-6)'],
      ['Taste of Camp 1', undefined, 'Taste of Camp 1'],
      ['Session 2a', undefined, 'Session 2a'],
      ['Session 3b', undefined, 'Session 3b'],
      ['Taste of Camp 2', undefined, 'Taste of Camp 2'],
      ['All-Gender Cabin-Session 2 (7th & 8th grades)', undefined, 'AG 2 (7-8)'],
      ['All-Gender Cabin-Session 4 (4th - 6th grades)', undefined, 'AG 4 (4-6)'],
      ['Session 4 (All-Gender Cabin)-6th & 7th grades', undefined, 'AG 4 (6-7)'],
      ['Session B (All-Gender Cabins)', undefined, 'AG B'],
      ['All-Gender Cabin-Session 3 (Grades 6-8)', undefined, 'AG 3'],
      ['AG Session 4', undefined, 'AG 4'],
      ['Teen Adventure Quests', undefined, 'Teen Adventure Quests'],
      [
        'Quest Session 2: Backpacking the High Sierra',
        undefined,
        'Quest Session 2: Backpacking the High Sierra',
      ],
      ['SCIT: Rising 12th', undefined, 'SCIT: Rising 12th'],
      ['TLI: Fall Interns', undefined, 'TLI: Fall Interns'],
      ['Family Camp 1: Memorial Day Weekend', undefined, 'Family Camp 1: Memorial Day Weekend'],
      [
        'Family Camp 5: JFAM Weekend (w/ kids 10 and under)',
        undefined,
        'Family Camp 5: JFAM Weekend (w/ kids 10 and under)',
      ],
      [
        'Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)',
        undefined,
        'Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)',
      ],
      ['Family Camp 10: Labor Day Weekend', undefined, 'Family Camp 10: Labor Day Weekend'],
      ['Spring Family Camp', undefined, 'Spring Family Camp'],
      ['Fall Family Camp II', undefined, 'Fall Family Camp II'],
      ['JFAM Winter Family Camp', undefined, 'JFAM Winter Family Camp'],
      ['Ready, Set, Camp', undefined, 'Ready, Set, Camp'],
      ['Spring Family Retreat', undefined, 'Spring Family Retreat'],
      ["Women's Weekend (3 nights)", undefined, "Women's Weekend (3 nights)"],
      ["Men's Weekend", undefined, "Men's Weekend"],
      [
        'Divorce & Discovery: A Jewish Healing Retreat (full price)',
        undefined,
        'Divorce & Discovery: A Jewish Healing Retreat (full price)',
      ],
      ['Spring Service Weekend ($54 fee)', undefined, 'Spring Service Weekend ($54 fee)'],
      ['', undefined, ''],
    ],
  },
  {
    group: 'matrix',
    form: 'matrix',
    was: 'formatAgSessionLabel(name)',
    sites: ['metrics/registration/SessionAvailability.tsx (AG matrix row)'],
    legacy: (name) => formatAgSessionLabel(name),
    pins: [
      ['Session 2', undefined, 'Session 2'],
      ['Session 3', undefined, 'Session 3'],
      ['Session 2 (Grades 4-6)', undefined, 'Session 2 (Grades 4-6)'],
      ['Taste of Camp 1', undefined, 'Taste of Camp 1'],
      ['Session 2a', undefined, 'Session 2a'],
      ['Session 3b', undefined, 'Session 3b'],
      ['Taste of Camp 2', undefined, 'Taste of Camp 2'],
      ['All-Gender Cabin-Session 2 (7th & 8th grades)', undefined, 'AG Session 2 (7th & 8th)'],
      ['All-Gender Cabin-Session 4 (4th - 6th grades)', undefined, 'AG Session 4 (4th - 6th)'],
      ['Session 4 (All-Gender Cabin)-6th & 7th grades', undefined, 'AG Session 4 (6th & 7th)'],
      ['Session B (All-Gender Cabins)', undefined, 'AG Session B'],
      ['All-Gender Cabin-Session 3 (Grades 6-8)', undefined, 'AG Session 3'],
      ['AG Session 4', undefined, 'AG Session 4'],
      ['Teen Adventure Quests', undefined, 'Teen Adventure Quests'],
      [
        'Quest Session 2: Backpacking the High Sierra',
        undefined,
        'Quest Session 2: Backpacking the High Sierra',
      ],
      ['SCIT: Rising 12th', undefined, 'SCIT: Rising 12th'],
      ['TLI: Fall Interns', undefined, 'TLI: Fall Interns'],
      ['Family Camp 1: Memorial Day Weekend', undefined, 'Family Camp 1: Memorial Day Weekend'],
      [
        'Family Camp 5: JFAM Weekend (w/ kids 10 and under)',
        undefined,
        'Family Camp 5: JFAM Weekend (w/ kids 10 and under)',
      ],
      [
        'Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)',
        undefined,
        'Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)',
      ],
      ['Family Camp 10: Labor Day Weekend', undefined, 'Family Camp 10: Labor Day Weekend'],
      ['Spring Family Camp', undefined, 'Spring Family Camp'],
      ['Fall Family Camp II', undefined, 'Fall Family Camp II'],
      ['JFAM Winter Family Camp', undefined, 'JFAM Winter Family Camp'],
      ['Ready, Set, Camp', undefined, 'Ready, Set, Camp'],
      ['Spring Family Retreat', undefined, 'Spring Family Retreat'],
      ["Women's Weekend (3 nights)", undefined, "Women's Weekend (3 nights)"],
      ["Men's Weekend", undefined, "Men's Weekend"],
      [
        'Divorce & Discovery: A Jewish Healing Retreat (full price)',
        undefined,
        'Divorce & Discovery: A Jewish Healing Retreat (full price)',
      ],
      ['Spring Service Weekend ($54 fee)', undefined, 'Spring Service Weekend ($54 fee)'],
      ['', undefined, ''],
    ],
  },
  {
    group: 'title',
    form: 'title',
    was: 'getSessionDisplayNameFromString(name, type)',
    sites: [
      'CamperDetailsPanel.tsx (journey row)',
      'camper/SiblingsPanel.tsx (x2)',
      'camper/journeyRowModel.ts (camper journey)',
    ],
    legacy: (name, type) => getSessionDisplayNameFromString(name, type),
    pins: [
      ['Session 2', 'main', 'Session 2'],
      ['Session 3', 'main', 'Session 3'],
      ['Session 2 (Grades 4-6)', 'main', 'Session 2 (Grades 4-6)'],
      ['Taste of Camp 1', 'main', 'Taste of Camp 1'],
      ['Session 2a', 'embedded', 'Session 2a'],
      ['Session 3b', 'embedded', 'Session 3b'],
      ['Taste of Camp 2', 'embedded', 'Taste of Camp 2'],
      ['All-Gender Cabin-Session 2 (7th & 8th grades)', 'ag', 'Session 2'],
      ['All-Gender Cabin-Session 4 (4th - 6th grades)', 'ag', 'Session 4'],
      ['Session 4 (All-Gender Cabin)-6th & 7th grades', 'ag', 'Session 4'],
      ['Session B (All-Gender Cabins)', 'ag', 'Session B (All-Gender Cabins)'],
      ['All-Gender Cabin-Session 3 (Grades 6-8)', 'ag', 'Session 3'],
      ['AG Session 4', 'ag', 'Session 4'],
      ['Teen Adventure Quests', 'quest', 'Teen Adventure Quests'],
      [
        'Quest Session 2: Backpacking the High Sierra',
        'quest',
        'Quest Session 2: Backpacking the High Sierra',
      ],
      ['SCIT: Rising 12th', 'scit', 'SCIT: Rising 12th'],
      ['TLI: Fall Interns', 'tli', 'TLI: Fall Interns'],
      ['Family Camp 1: Memorial Day Weekend', 'family', 'Family Camp 1'],
      ['Family Camp 5: JFAM Weekend (w/ kids 10 and under)', 'family', 'Family Camp 5'],
      ['Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)', 'family', 'Family Camp 8'],
      ['Family Camp 10: Labor Day Weekend', 'family', 'Family Camp 10'],
      ['Spring Family Camp', 'family', 'Family Camp 1'],
      ['Fall Family Camp II', 'family', 'Family Camp 5'],
      ['JFAM Winter Family Camp', 'family', 'Winter Family Camp'],
      ['Ready, Set, Camp', 'family', 'Ready, Set, Camp'],
      ['Spring Family Retreat', 'family', 'Spring Family Retreat'],
      ["Women's Weekend (3 nights)", 'adult', "Women's Weekend"],
      ["Men's Weekend", 'adult', "Men's Weekend"],
      [
        'Divorce & Discovery: A Jewish Healing Retreat (full price)',
        'adult',
        'Divorce & Discovery',
      ],
      ['Spring Service Weekend ($54 fee)', 'adult', 'Spring Service Weekend'],
      ['', '', 'Unknown Session'],
    ],
  },
  {
    group: 'chart',
    form: 'chart',
    was: 'getSessionChartLabel(name, undefined, lookup)',
    sites: [
      'metrics/registration/RegistrationOverview.tsx (session table)',
      'utils/metricsTransforms.ts (x3 chart points)',
    ],
    legacy: (name) => getSessionChartLabel(name, undefined),
    pins: [
      ['Session 2', undefined, 'Session 2'],
      ['Session 3', undefined, 'Session 3'],
      ['Session 2 (Grades 4-6)', undefined, 'Session 2 (4-6)'],
      ['Taste of Camp 1', undefined, 'Taste of Camp 1'],
      ['Session 2a', undefined, 'Session 2a'],
      ['Session 3b', undefined, 'Session 3b'],
      ['Taste of Camp 2', undefined, 'Taste of Camp 2'],
      ['All-Gender Cabin-Session 2 (7th & 8th grades)', undefined, 'All-Gender 2'],
      ['All-Gender Cabin-Session 4 (4th - 6th grades)', undefined, 'All-Gender 4'],
      ['Session 4 (All-Gender Cabin)-6th & 7th grades', undefined, 'All-Gender 4'],
      ['Session B (All-Gender Cabins)', undefined, 'All-Gender'],
      ['All-Gender Cabin-Session 3 (Grades 6-8)', undefined, 'All-Gender 3 (6-8)'],
      ['AG Session 4', undefined, 'All-Gender 4'],
      ['Teen Adventure Quests', undefined, 'Teen Adventure Quests'],
      ['Quest Session 2: Backpacking the High Sierra', undefined, 'Quest Session 2: Backp...'],
      ['SCIT: Rising 12th', undefined, 'SCIT: Rising 12th'],
      ['TLI: Fall Interns', undefined, 'TLI: Fall Interns'],
      ['Family Camp 1: Memorial Day Weekend', undefined, 'Family Camp 1: Memoria...'],
      [
        'Family Camp 5: JFAM Weekend (w/ kids 10 and under)',
        undefined,
        'Family Camp 5: JFAM We...',
      ],
      [
        'Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)',
        undefined,
        'Family Camp 8: JFAM We...',
      ],
      ['Family Camp 10: Labor Day Weekend', undefined, 'Family Camp 10: Labor ...'],
      ['Spring Family Camp', undefined, 'Spring Family Camp'],
      ['Fall Family Camp II', undefined, 'Fall Family Camp II'],
      ['JFAM Winter Family Camp', undefined, 'JFAM Winter Family Camp'],
      ['Ready, Set, Camp', undefined, 'Ready, Set, Camp'],
      ['Spring Family Retreat', undefined, 'Spring Family Retreat'],
      ["Women's Weekend (3 nights)", undefined, "Women's Weekend (3 nig..."],
      ["Men's Weekend", undefined, "Men's Weekend"],
      [
        'Divorce & Discovery: A Jewish Healing Retreat (full price)',
        undefined,
        'Divorce & Discovery: A...',
      ],
      ['Spring Service Weekend ($54 fee)', undefined, 'Spring Service Weekend...'],
      ['', undefined, 'Unknown'],
    ],
  },
  {
    group: 'tiny-camper-card',
    form: 'tiny',
    was: 'getSessionShorthand(name, type)',
    sites: ['CamperCard.tsx (last-year line; at-camp types only, per CamperHistoryProvider)'],
    legacy: (name, type) => getSessionShorthand(name, type),
    pins: [
      ['Session 2', 'main', '2'],
      ['Session 3', 'main', '3'],
      ['Session 2 (Grades 4-6)', 'main', '2'],
      ['Taste of Camp 1', 'main', 'Taste 1'],
      ['Session 2a', 'embedded', '2a'],
      ['Session 3b', 'embedded', '3b'],
      ['Taste of Camp 2', 'embedded', 'Taste 2'],
      ['All-Gender Cabin-Session 2 (7th & 8th grades)', 'ag', '2'],
      ['All-Gender Cabin-Session 4 (4th - 6th grades)', 'ag', '4'],
      ['Session 4 (All-Gender Cabin)-6th & 7th grades', 'ag', '4'],
      ['Session B (All-Gender Cabins)', 'ag', 'Session'],
      ['All-Gender Cabin-Session 3 (Grades 6-8)', 'ag', '3'],
      ['AG Session 4', 'ag', '4'],
      ['', '', ''],
    ],
  },
  {
    group: 'tiny-untyped',
    form: 'tiny',
    was: 'getSessionShorthand(name)',
    sites: ['bunkGraphStyles.ts (last-year node label)'],
    legacy: (name) => getSessionShorthand(name),
    pins: [
      ['Session 2', undefined, '2'],
      ['Session 3', undefined, '3'],
      ['Session 2 (Grades 4-6)', undefined, '2'],
      ['Taste of Camp 1', undefined, 'Taste 1'],
      ['Session 2a', undefined, '2a'],
      ['Session 3b', undefined, '3b'],
      ['Taste of Camp 2', undefined, 'Taste 2'],
      ['All-Gender Cabin-Session 2 (7th & 8th grades)', undefined, '2'],
      ['All-Gender Cabin-Session 4 (4th - 6th grades)', undefined, '4'],
      ['Session 4 (All-Gender Cabin)-6th & 7th grades', undefined, '4'],
      ['Session B (All-Gender Cabins)', undefined, 'Session'],
      ['All-Gender Cabin-Session 3 (Grades 6-8)', undefined, '3'],
      ['AG Session 4', undefined, '4'],
      ['Teen Adventure Quests', undefined, 'Quest'],
      ['Quest Session 2: Backpacking the High Sierra', undefined, 'Quest'],
      ['SCIT: Rising 12th', undefined, '12t'],
      ['TLI: Fall Interns', undefined, 'TLI:'],
      ['Family Camp 1: Memorial Day Weekend', undefined, '1'],
      ['Family Camp 5: JFAM Weekend (w/ kids 10 and under)', undefined, '5'],
      ['Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)', undefined, '8'],
      ['Family Camp 10: Labor Day Weekend', undefined, '10'],
      ['Spring Family Camp', undefined, 'Spring'],
      ['Fall Family Camp II', undefined, 'Fall'],
      ['JFAM Winter Family Camp', undefined, 'JFAM'],
      ['Ready, Set, Camp', undefined, 'Ready,'],
      ['Spring Family Retreat', undefined, 'Spring'],
      ["Women's Weekend (3 nights)", undefined, '3'],
      ["Men's Weekend", undefined, "Men's"],
      ['Divorce & Discovery: A Jewish Healing Retreat (full price)', undefined, 'Divorce'],
      ['Spring Service Weekend ($54 fee)', undefined, '54'],
      ['', undefined, ''],
    ],
  },
  {
    group: 'identity',
    form: 'identity',
    was: 'shortWeekendName(name) / splitWeekendName(name).short',
    sites: [
      'pages/WeekendRosterPage.tsx (x3: title switcher label + options, cabin-weekend entry)',
      'pages/WeekendSessionList.tsx (row title)',
      'hooks/useSessionAttributionQueue.ts (candidate pill)',
    ],
    legacy: (name) => shortWeekendName(name),
    pins: [
      ['Family Camp 1: Memorial Day Weekend', 'family', 'Family Camp 1'],
      ['Family Camp 5: JFAM Weekend (w/ kids 10 and under)', 'family', 'Family Camp 5'],
      ['Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)', 'family', 'Family Camp 8'],
      ['Family Camp 10: Labor Day Weekend', 'family', 'Family Camp 10'],
      ['Spring Family Camp', 'family', 'Spring Family Camp'],
      ['Fall Family Camp II', 'family', 'Fall Family Camp II'],
      ['JFAM Winter Family Camp', 'family', 'JFAM Winter Family Camp'],
      ['Ready, Set, Camp', 'family', 'Ready, Set, Camp'],
      ['Spring Family Retreat', 'family', 'Spring Family Retreat'],
      ["Women's Weekend (3 nights)", 'adult', "Women's Weekend (3 nights)"],
      ["Men's Weekend", 'adult', "Men's Weekend"],
      [
        'Divorce & Discovery: A Jewish Healing Retreat (full price)',
        'adult',
        'Divorce & Discovery',
      ],
      ['Spring Service Weekend ($54 fee)', 'adult', 'Spring Service Weekend ($54 fee)'],
      ['', '', ''],
    ],
  },
  {
    group: 'tiny-family',
    form: 'tiny',
    was: 'weekendLabel(name)',
    sites: [
      'weekend/HouseholdJourneyCard.tsx (x2)',
      'weekend/HouseholdYearMembersModal.tsx (weekend tabs)',
    ],
    legacy: (name) => weekendLabel(name),
    pins: [
      ['Family Camp 1: Memorial Day Weekend', 'family', 'FC1'],
      ['Family Camp 5: JFAM Weekend (w/ kids 10 and under)', 'family', 'FC5'],
      ['Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)', 'family', 'FC8'],
      ['Family Camp 10: Labor Day Weekend', 'family', 'FC10'],
      ['Spring Family Camp', 'family', 'FC1'],
      ['Fall Family Camp II', 'family', 'FC5'],
      ['JFAM Winter Family Camp', 'family', 'WFC'],
      ['Ready, Set, Camp', 'family', 'RSC'],
      ['Spring Family Retreat', 'family', 'Spring FR'],
      ['', 'family', ''],
    ],
  },
]

describe('#2763 call-site pins — the output before the move', () => {
  for (const group of CALL_SITE_GROUPS) {
    describe(`${group.group}: ${group.was}`, () => {
      it.each(group.pins)('%s (%s) → %s', (name, sessionType, expected) => {
        expect(group.legacy(name, sessionType)).toBe(expected)
      })
    })
  }
})

describe('#2763 call-site pins — the same output through sessionName', () => {
  for (const group of CALL_SITE_GROUPS) {
    describe(`${group.group}: sessionName(name, type, '${group.form}')`, () => {
      it.each(group.pins)('%s (%s) → %s', (name, sessionType, expected) => {
        expect(sessionName(name, sessionType, group.form)).toBe(expected)
      })
    })
  }
})

/**
 * The record adapters. These take a session RECORD, not a name, because what
 * they add is record-level: a missing name's fallback ('AG', 'Quest', null)
 * and, for the 'full' pair, the AG -> parent-session lookup. They stay as
 * adapters after the move; these pins are what proves their name half moved
 * intact.
 */
describe('#2763 record-adapter pins', () => {
  const s = (partial: Record<string, unknown>) => partial as Session

  describe('getSessionShortName — CamperDetail.tsx (x2), CamperDetailsPanel.tsx (header chip, enrollment chips)', () => {
    const pins: Array<readonly [name: string, sessionType: string, expected: string]> = [
      ['Session 2', 'main', 'Session 2'],
      ['Session 3', 'main', 'Session 3'],
      ['Session 2 (Grades 4-6)', 'main', 'Session 2 (Grades 4-6)'],
      ['Taste of Camp 1', 'main', 'Taste of Camp 1'],
      ['Session 2a', 'embedded', 'Session 2a'],
      ['Session 3b', 'embedded', 'Session 3b'],
      ['Taste of Camp 2', 'embedded', 'Taste of Camp 2'],
      ['All-Gender Cabin-Session 2 (7th & 8th grades)', 'ag', 'AG 2 (7-8)'],
      ['All-Gender Cabin-Session 4 (4th - 6th grades)', 'ag', 'AG 4 (4-6)'],
      ['Session 4 (All-Gender Cabin)-6th & 7th grades', 'ag', 'AG 4 (6-7)'],
      ['Session B (All-Gender Cabins)', 'ag', 'AG B'],
      ['All-Gender Cabin-Session 3 (Grades 6-8)', 'ag', 'AG 3'],
      ['AG Session 4', 'ag', 'AG 4'],
      ['Teen Adventure Quests', 'quest', 'Teen Adventure Quests'],
      [
        'Quest Session 2: Backpacking the High Sierra',
        'quest',
        'Quest Session 2: Backpacking the High Sierra',
      ],
      ['SCIT: Rising 12th', 'scit', 'SCIT: Rising 12th'],
      ['TLI: Fall Interns', 'tli', 'TLI: Fall Interns'],
      ['Family Camp 1: Memorial Day Weekend', 'family', 'Family Camp 1: Memorial Day Weekend'],
      [
        'Family Camp 5: JFAM Weekend (w/ kids 10 and under)',
        'family',
        'Family Camp 5: JFAM Weekend (w/ kids 10 and under)',
      ],
      [
        'Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)',
        'family',
        'Family Camp 8: JFAM Weekend w/ SFJCC (w/ kids 10 and under)',
      ],
      ['Family Camp 10: Labor Day Weekend', 'family', 'Family Camp 10: Labor Day Weekend'],
      ['Spring Family Camp', 'family', 'Spring Family Camp'],
      ['Fall Family Camp II', 'family', 'Fall Family Camp II'],
      ['JFAM Winter Family Camp', 'family', 'JFAM Winter Family Camp'],
      ['Ready, Set, Camp', 'family', 'Ready, Set, Camp'],
      ['Spring Family Retreat', 'family', 'Spring Family Retreat'],
      ["Women's Weekend (3 nights)", 'adult', "Women's Weekend"],
      ["Men's Weekend", 'adult', "Men's Weekend"],
      [
        'Divorce & Discovery: A Jewish Healing Retreat (full price)',
        'adult',
        'Divorce & Discovery',
      ],
      ['Spring Service Weekend ($54 fee)', 'adult', 'Spring Service Weekend'],
      ['', '', ''],
    ]
    it.each(pins)('%s (%s) → %s', (name, sessionType, expected) => {
      expect(getSessionShortName({ session_type: sessionType, name })).toBe(expected)
    })

    it('keeps each missing-name fallback', () => {
      expect(getSessionShortName(undefined)).toBe(null)
      expect(getSessionShortName({ session_type: 'ag' })).toBe('AG')
      expect(getSessionShortName({ session_type: 'ag', name: '' })).toBe('AG')
      expect(getSessionShortName({ session_type: 'quest' })).toBe('Quest')
      expect(getSessionShortName({ session_type: 'quest', name: '' })).toBe('')
      expect(getSessionShortName({ session_type: 'adult' })).toBe(null)
      expect(getSessionShortName({ session_type: 'adult', name: '' })).toBe(null)
      expect(getSessionShortName({ session_type: 'main' })).toBe(null)
      expect(getSessionShortName({ session_type: 'main', name: '' })).toBe('')
    })

    it('does NOT infer AG from the name of an untyped record', () => {
      // A record reaching the chip without a session_type gets its raw name.
      // The metrics rows (which have no type at all) DO infer AG from the
      // name; the record path never has. This is the pin that keeps the two
      // from being merged by accident.
      expect(getSessionShortName({ name: 'All-Gender Cabin-Session 2 (7th & 8th grades)' })).toBe(
        'All-Gender Cabin-Session 2 (7th & 8th grades)'
      )
    })
  })

  const all: Session[] = [
    s({ name: 'Session 2', session_type: 'main', cm_id: 200 }),
    s({ name: 'Teen Adventure Quests', session_type: 'quest', cm_id: 500 }),
    s({ name: 'Family Camp 1: Memorial Day Weekend', session_type: 'family', cm_id: 900 }),
    s({
      name: 'All-Gender Cabin-Session 2 (7th & 8th grades)',
      session_type: 'ag',
      parent_id: 200,
      cm_id: 201,
    }),
    s({
      name: 'All-Gender Cabin-Session 9 (7th & 8th grades)',
      session_type: 'ag',
      parent_id: 999,
      cm_id: 901,
    }),
    s({ name: '', session_type: 'main', cm_id: 300 }),
    s({ name: 'All-Gender Cabin-Session 3', session_type: 'ag', parent_id: 300, cm_id: 301 }),
    s({ name: '', session_type: 'quest', cm_id: 501 }),
  ]
  const byId = (cmId: number) => all.find((x) => x.cm_id === cmId)

  it('getFormattedSessionName — SessionList.tsx, SessionHeader.tsx (x2)', () => {
    expect(getFormattedSessionName(byId(200), all)).toBe('Session 2')
    expect(getFormattedSessionName(byId(500), all)).toBe('Teen Adventure Quests')
    expect(getFormattedSessionName(byId(900), all)).toBe('Family Camp 1: Memorial Day Weekend')
    expect(getFormattedSessionName(byId(201), all)).toBe('Session 2')
    expect(getFormattedSessionName(byId(201))).toBe('All-Gender Cabin-Session 2 (7th & 8th grades)')
    expect(getFormattedSessionName(byId(901), all)).toBe(
      'All-Gender Cabin-Session 9 (7th & 8th grades)'
    )
    expect(getFormattedSessionName(byId(301), all)).toBe('All-Gender Cabin-Session 3')
    expect(getFormattedSessionName(byId(501), all)).toBe('Unknown Session')
    expect(getFormattedSessionName(undefined, all)).toBe('Unknown Session')
  })

  it('getSessionDisplayName — AllCampersView.tsx (x5)', () => {
    expect(getSessionDisplayName(byId(200), all)).toBe('Session 2')
    expect(getSessionDisplayName(byId(500), all)).toBe('Teen Adventure Quests')
    expect(getSessionDisplayName(byId(900), all)).toBe('Family Camp 1: Memorial Day Weekend')
    expect(getSessionDisplayName(byId(201), all)).toBe('Session 2')
    expect(getSessionDisplayName(byId(201))).toBe('All-Gender Cabin-Session 2 (7th & 8th grades)')
    expect(getSessionDisplayName(byId(901), all)).toBe(
      'All-Gender Cabin-Session 9 (7th & 8th grades)'
    )
    expect(getSessionDisplayName(byId(301), all)).toBe('Unknown Session')
    expect(getSessionDisplayName(byId(501), all)).toBe('Quest')
    expect(getSessionDisplayName(undefined, all)).toBe('Unknown Session')
  })
})

/**
 * The slug -> label coupling (#2763 cluster note). A numbered weekend's tiny
 * label IS its URL slug uppercased, so a change to the slug rule moves a
 * rendered label. These pin both halves as literals, so such a change fails
 * here rather than silently renaming "FC1" on the household journey card.
 */
describe('#2763 slug -> label coupling', () => {
  it.each([
    ['Family Camp 1: Memorial Day Weekend', 'fc1', 'FC1'],
    ['Family Camp 5: JFAM Weekend (w/ kids 10 and under)', 'fc5', 'FC5'],
    ['Family Camp 10: Labor Day Weekend', 'fc10', 'FC10'],
    ['JFAM 10', 'j10', 'J10'],
  ])('%s: slug %s, label %s', (name, slug, label) => {
    expect(weekendSlug(name)).toBe(slug)
    expect(weekendLabel(name)).toBe(label)
    expect(weekendLabel(name)).toBe(weekendSlug(name).toUpperCase())
  })
})
